a=int(input("Enter first number(a):"))
b=int(input("Enter second number(b):"))
print("Addition(a+b):",a+b)
print(",subtraction(a-b):",a-b)
print("Multiplication(a*b):",a*b)
print("Normal Division(a/b):",a/b)
print("Modulus/Remainder(a%b):",a%b)
print("Floor Division(a//b):",a//b)
print("Exponentiation/power(a**b):",a**b)